### ISSUE TITLE
Note 20 Ultra + Pen Support

### ISSUE THREAD

**Issue by plukic** [mirza-ito/DotNetPlayground#4]
Is it runnable on Note 20 Ultra Octa-core (1x3.0 GHz Kryo 585 & 3x2.42 GHz Kryo 585 & 4x1.8 GHz Kryo 585) with Qualcomm SM8250 Snapdragon?
I believe not.
Please fix

**Comment by mirza-ito** [comment]
All issues regarding android devices will be ignored.
